# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Colour
version:      0.01
version_from: lib/Template/Plugin/Colour.pm
installdirs:  site
requires:
    Template:                      2.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
